# SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, 
# DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
 
# FROM USED_GOODS_BOARD b, USED_GOODS_REPLY r

# where b.BOARD_ID = r.BOARD_ID and
# DATE_FORMAT(r.CREATED_DATE, '%Y-%m') = '2022-10'
# ORDER BY r.CREATED_DATE, b.TITLE

SELECT b.TITLE,b.BOARD_ID,r.REPLY_ID,r.WRITER_ID,r.CONTENTS,date_format(r.CREATED_DATE,"%Y-%m-%d") CREATED_DATE
from USED_GOODS_BOARD b, USED_GOODS_REPLY r 

where b.BOARD_ID = r.BOARD_ID and
date_format(b.CREATED_DATE,"%Y%m")=202210 

order by r.CREATED_DATE ,b.TITLE